// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuporteTI.Api.Data;

#nullable disable

namespace SuporteTI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuporteTI.Shared.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rede e Internet"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Contas e Acessos"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Geral"
                        });
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoInicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoTecnica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecnicoResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TecnicoResponsavelId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.HistoricoChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Resolveu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("HistoricoChats");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.SolucaoIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalavrasChave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SolucoesIA");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Descricao = "Tente fechar todos os programas que não está usando.|STEP|Utilize a \"Limpeza de Disco\" para liberar espaço.|STEP|Reinicie o computador.",
                            PalavrasChave = "lento, travando"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 3,
                            Descricao = "Verifique se o cabo de rede está bem conectado ao computador e ao roteador.|STEP|Tente reiniciar seu modem e roteador (desligue da tomada por 30 segundos e ligue novamente).|STEP|No caso de notebook, veja se o Wi-Fi está ativado.",
                            PalavrasChave = "conectar à internet, sem internet, sem conexão, caiu"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descricao = "Na tela de login do seu e-mail, clique no link \"Esqueci minha senha\" ou \"Recuperar senha\".|STEP|Siga as instruções para criar uma nova senha.",
                            PalavrasChave = "esqueci minha senha, senha de e-mail, recuperar senha"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descricao = "Veja se a impressora está ligada e conectada ao computador.|STEP|Verifique se os níveis de tinta ou toner estão bons.|STEP|Tente reiniciar a impressora e o computador.",
                            PalavrasChave = "imprimir, impressora"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descricao = "Verifique a Lixeira do seu computador.|STEP|Use a barra de pesquisa para procurar pelo nome do arquivo.|STEP|Veja se você não moveu os arquivos para outra pasta sem querer.",
                            PalavrasChave = "arquivos sumiram, perdi arquivo, arquivo desapareceu"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Descricao = "Pressione as teclas Ctrl + Alt + Del e escolha o \"Gerenciador de Tarefas\".|STEP|Na lista, encontre o programa travado, clique nele e depois em \"Finalizar tarefa\".|STEP|Se não funcionar, reinicie o computador.",
                            PalavrasChave = "programa travou, não responde"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Descricao = "Verifique se os programas e o sistema operacional estão atualizados.|STEP|Faça uma verificação completa com seu antivírus.|STEP|Veja se o computador não está esquentando demais.",
                            PalavrasChave = "travando com frequência, travamentos"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Descricao = "Tente acessar outros sites para ver se sua internet está funcionando.|STEP|Limpe o cache e os cookies do seu navegador.|STEP|Tente usar um navegador diferente (Chrome, Firefox, Edge).",
                            PalavrasChave = "acessar um site específico, site não abre"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Descricao = "Marque sempre as mensagens indesejadas como \"Spam\" ou \"Lixo Eletrônico\".|STEP|Evite colocar seu e-mail em sites públicos.|STEP|Cancele a inscrição de newsletters que você não lê mais.",
                            PalavrasChave = "muito spam, e-mail spam"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Descricao = "Siga as instruções do antivírus para remover ou colocar a ameaça em quarentena.|STEP|Depois, faça uma verificação completa no computador.|STEP|Mantenha seu antivírus sempre atualizado.",
                            PalavrasChave = "vírus, antivírus avisou"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 1,
                            Descricao = "Anote o código de erro que aparece na tela, se possível.|STEP|Reinicie o computador.|STEP|Se acontecer de novo, procure por atualizações de drivers e do sistema operacional.",
                            PalavrasChave = "tela azul, blue screen"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 3,
                            Descricao = "Veja se você está conectado à rede da empresa (cabo ou Wi-Fi).|STEP|Verifique se você tem permissão para acessar aquela pasta.|STEP|Tente reiniciar o seu computador.",
                            PalavrasChave = "arquivo da rede, pasta da rede"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            Descricao = "Verifique se o cabo está bem conectado na porta USB.|STEP|Se for sem fio, verifique as pilhas ou a bateria.|STEP|Tente conectar em outra porta USB.",
                            PalavrasChave = "mouse parou, teclado parou"
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 3,
                            Descricao = "Feche outros programas e abas da internet que você não esteja usando.|STEP|Verifique as configurações de áudio e vídeo dentro do programa da reunião.|STEP|Tente usar um fone de ouvido com microfone.",
                            PalavrasChave = "videoconferência, reunião ruim, som ruim, imagem ruim"
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 2,
                            Descricao = "Clique com o botão direito no instalador e escolha \"Executar como administrador\".|STEP|Desative o antivírus temporariamente durante a instalação (lembre de ligar de novo depois).|STEP|Baixe o arquivo de instalação novamente, ele pode estar corrompido.",
                            PalavrasChave = "instalar um programa, não instala"
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 1,
                            Descricao = "Desinstale programas que você não usa mais.|STEP|Apague arquivos desnecessários, principalmente da pasta \"Downloads\".|STEP|Use a \"Limpeza de Disco\" para remover arquivos temporários.",
                            PalavrasChave = "hd cheio, disco rígido cheio, sem espaço"
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 2,
                            Descricao = "Clique na data e hora na barra de tarefas e escolha \"Ajustar data/hora\".|STEP|Verifique se o fuso horário está correto.|STEP|Ative a opção para acertar o relógio automaticamente pela internet.",
                            PalavrasChave = "data e hora erradas"
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 2,
                            Descricao = "Verifique se você tem um programa instalado para abrir esse tipo de arquivo.|STEP|Para PDF, instale o Adobe Acrobat Reader.|STEP|Para DOCX, você pode usar o Word ou o LibreOffice.",
                            PalavrasChave = "abrir pdf, abrir word, abrir docx"
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 3,
                            Descricao = "Desconecte da rede os aparelhos que não estão em uso.|STEP|Reinicie o seu roteador (desligue da tomada por 30 segundos).|STEP|Aproxime-se do roteador para ver se o sinal melhora.",
                            PalavrasChave = "wi-fi lenta, wifi lento"
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 1,
                            Descricao = "Verifique se o carregador está bem conectado no notebook e na tomada.|STEP|Veja se alguma luz acende quando você conecta o carregador.|STEP|Se a bateria for removível, tente tirar e ligar o notebook direto na tomada.",
                            PalavrasChave = "notebook não liga"
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 1,
                            Descricao = "Verifique se o volume não está no mudo ou muito baixo.|STEP|Veja se o fone de ouvido ou as caixas de som estão bem conectados.|STEP|Reinicie o computador.",
                            PalavrasChave = "sem som, computador mudo"
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 3,
                            Descricao = "Verifique se a data e a hora do seu computador estão corretas.|STEP|Limpe o cache e os cookies do seu navegador.|STEP|Veja se o seu navegador de internet está atualizado.",
                            PalavrasChave = "cadeado https, site https"
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 1,
                            Descricao = "Verifique se o computador não está superaquecendo.|STEP|Procure por atualizações do sistema operacional e de drivers.|STEP|Faça uma verificação completa com o antivírus.",
                            PalavrasChave = "reinicia sozinho"
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 1,
                            Descricao = "Verifique se o cabo de vídeo (HDMI, VGA) está bem conectado no monitor e no computador.|STEP|Tente usar um cabo diferente.|STEP|Atualize o driver da placa de vídeo.",
                            PalavrasChave = "tela piscando"
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 4,
                            Descricao = "Veja se a tecla Caps Lock (letras maiúsculas) não está ativada.|STEP|Tente usar a opção de redefinir a senha, se houver.|STEP|Entre em contato com o suporte de TI da sua empresa.",
                            PalavrasChave = "conta do trabalho, não entro na conta"
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 3,
                            Descricao = "Verifique se a sua internet está funcionando normalmente.|STEP|Confira se seu usuário e senha da VPN estão corretos.|STEP|Reinicie o programa da VPN e o seu computador.",
                            PalavrasChave = "vpn não conecta"
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 3,
                            Descricao = "Verifique se o equipamento (impressora, servidor) está ligado.|STEP|Confirme se você tem permissão para acessar esse recurso.|STEP|Peça ajuda ao administrador da rede.",
                            PalavrasChave = "recurso da rede, impressora da rede, pasta da rede"
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 1,
                            Descricao = "Verifique se as saídas de ar do computador não estão bloqueadas por poeira ou objetos.|STEP|Veja se o computador está em um local bem ventilado.|STEP|Se o barulho for muito alto, pode ser um problema no ventilador interno.",
                            PalavrasChave = "muito barulho, barulhento"
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 1,
                            Descricao = "Verifique se o CD/DVD que você está usando é do tipo gravável (CD-R, DVD-R).|STEP|Tente gravar em uma velocidade mais baixa.|STEP|Use um CD/DVD de outra marca para testar.",
                            PalavrasChave = "gravar cd, gravar dvd"
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 1,
                            Descricao = "Veja se o computador está realmente ligado.|STEP|Verifique se o cabo de vídeo está bem conectado no monitor e no computador.|STEP|Se tiver uma placa de vídeo dedicada, conecte o cabo nela, e não na placa-mãe.",
                            PalavrasChave = "sem sinal, monitor sem sinal"
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 3,
                            Descricao = "Tente acessar outros sites para ver se sua internet está normal.|STEP|Verifique se o serviço não está fora do ar para todo mundo.|STEP|Limpe o cache e os cookies do seu navegador.",
                            PalavrasChave = "serviço online, site fora do ar"
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 1,
                            Descricao = "Veja se você não desativou o touchpad sem querer por alguma tecla de atalho (geralmente Fn + uma das teclas F1 a F12).|STEP|Reinicie o notebook.|STEP|Conecte um mouse USB para ver se o problema é só no touchpad.",
                            PalavrasChave = "touchpad, mouse do notebook"
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 2,
                            Descricao = "Não clique em nada nesses alertas.|STEP|Feche as janelas pop-up.|STEP|Faça uma verificação completa com seu antivírus e um programa anti-malware.",
                            PalavrasChave = "pop-ups, alertas falsos, malware"
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 2,
                            Descricao = "Verifique se você tem bastante espaço livre no disco (HD).|STEP|Reinicie o computador e tente atualizar de novo.|STEP|Use a \"Solução de Problemas do Windows Update\" nas configurações do Windows.",
                            PalavrasChave = "atualizações do windows, windows update"
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 3,
                            Descricao = "Confira se a senha do Wi-Fi está correta.|STEP|No seu celular, vá nas configurações de Wi-Fi, mande \"esquecer a rede\" e conecte-se de novo.|STEP|Reinicie seu celular.",
                            PalavrasChave = "celular não conecta wi-fi"
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 3,
                            Descricao = "Verifique se sua internet está funcionando.|STEP|Veja se você ainda tem espaço de armazenamento livre na sua conta da nuvem.|STEP|Reinicie o programa de sincronização e o computador.",
                            PalavrasChave = "nuvem, google drive, onedrive, não sincroniza"
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 2,
                            Descricao = "Desative programas desnecessários da inicialização do sistema (pelo Gerenciador de Tarefas na aba \"Inicializar\").|STEP|Faça uma verificação completa de vírus.|STEP|Verifique se há espaço livre no disco rígido.",
                            PalavrasChave = "demora para ligar, boot lento"
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 3,
                            Descricao = "Verifique se o computador que você quer acessar está ligado e conectado à internet.|STEP|Confirme se a opção de \"Área de Trabalho Remota\" está ativada nesse computador.|STEP|Veja se você está digitando o nome ou IP do computador corretamente.",
                            PalavrasChave = "área de trabalho remota, rdp"
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 2,
                            Descricao = "Verifique sua conexão com a internet.|STEP|Confira se a senha da sua conta de e-mail está correta nas configurações do programa.|STEP|Reinicie o programa de e-mail e o computador.",
                            PalavrasChave = "programa de e-mail, outlook, thunderbird"
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 1,
                            Descricao = "Verifique se o scanner está ligado e conectado ao computador.|STEP|Reinicie o scanner e o computador.|STEP|Tente usar o programa de digitalização que veio com o scanner.",
                            PalavrasChave = "digitalizar, escanear, scanner"
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 2,
                            Descricao = "Faça uma verificação completa com seu antivírus e um programa anti-malware.|STEP|Verifique as extensões instaladas no navegador e remova as suspeitas.|STEP|Restaure as configurações do navegador para o padrão.",
                            PalavrasChave = "navegador, sites estranhos, redirecionamento"
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 1,
                            Descricao = "Diminua o brilho da tela.|STEP|Feche programas que você não está usando.|STEP|Desligue o Wi-Fi e o Bluetooth se não precisar deles.",
                            PalavrasChave = "bateria acaba rápido"
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 3,
                            Descricao = "Verifique se você está conectado à rede da empresa (cabo, Wi-Fi ou VPN).|STEP|Tente acessar outros recursos internos para ver se o problema é só com esse site.|STEP|Fale com o suporte de TI da sua empresa.",
                            PalavrasChave = "site interno, intranet"
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 1,
                            Descricao = "Tente conectar o dispositivo em outra porta USB.|STEP|Verifique se ele funciona em outro computador.|STEP|Reinicie o seu computador com o dispositivo conectado.",
                            PalavrasChave = "pen drive, hd externo, não reconhece"
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 2,
                            Descricao = "Feche outros programas que estejam abertos.|STEP|Verifique se há atualizações para esse programa.|STEP|Tente reiniciar o computador.",
                            PalavrasChave = "programa específico lento"
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 2,
                            Descricao = "Verifique as configurações de privacidade do seu sistema para ver se o programa da reunião tem permissão para gravar a tela.|STEP|Saia e entre novamente na reunião.|STEP|Reinicie o programa da reunião.",
                            PalavrasChave = "compartilhar tela, reunião"
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 2,
                            Descricao = "Se você tiver um backup, tente usar uma versão anterior do arquivo.|STEP|Veja se o programa que você usa para abrir o arquivo está atualizado.|STEP|Tente abrir o arquivo em outro computador.",
                            PalavrasChave = "arquivo corrompido, não abre"
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 2,
                            Descricao = "Use os estilos de formatação padrão (Ex: Título 1, Normal) para organizar o texto.|STEP|Tente copiar todo o texto e colar em um documento novo \"sem formatação\".|STEP|Reinicie o programa (Word, Writer, etc).",
                            PalavrasChave = "formatação, documento bagunçado"
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 4,
                            Descricao = "Verifique se o certificado não está vencido.|STEP|Certifique-se de que ele está instalado corretamente no computador ou navegador.|STEP|Tente reinstalar o certificado.",
                            PalavrasChave = "certificado digital"
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 1,
                            Descricao = "Veja se a impressora está ligada e conectada à mesma rede Wi-Fi que o seu computador.|STEP|No seu computador, vá em \"Configurações\" e depois \"Impressoras e Scanners\".|STEP|Clique em \"Adicionar uma impressora\" e veja se o computador a encontra sozinho.",
                            PalavrasChave = "instalar impressora de rede"
                        });
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDisponibilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user",
                            Nome = "Usuário Padrão",
                            Papel = "Usuario",
                            Senha = "usuario123",
                            Setor = "Vendas",
                            StatusDisponibilidade = "Offline",
                            Telefone = "11999999999"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tecnico",
                            Especialidade = "Redes",
                            Nome = "Técnico Padrão",
                            Papel = "Tecnico",
                            Senha = "tecnico123",
                            StatusDisponibilidade = "Online"
                        },
                        new
                        {
                            Id = 3,
                            Email = "gerencia",
                            Nome = "Gerente Admin",
                            Papel = "Gerencia",
                            Senha = "gerencia123",
                            Setor = "TI",
                            StatusDisponibilidade = "Online",
                            Telefone = "11888888888"
                        });
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.Chamado", b =>
                {
                    b.HasOne("SuporteTI.Shared.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("SuporteTI.Shared.Models.Usuario", "TecnicoResponsavel")
                        .WithMany("ChamadosAtendidos")
                        .HasForeignKey("TecnicoResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SuporteTI.Shared.Models.Usuario", "UsuarioSolicitante")
                        .WithMany("ChamadosAbertos")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("TecnicoResponsavel");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.HistoricoChat", b =>
                {
                    b.HasOne("SuporteTI.Shared.Models.Chamado", "Chamado")
                        .WithMany("Historico")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.SolucaoIA", b =>
                {
                    b.HasOne("SuporteTI.Shared.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.Chamado", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("SuporteTI.Shared.Models.Usuario", b =>
                {
                    b.Navigation("ChamadosAbertos");

                    b.Navigation("ChamadosAtendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
